# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(517, 369)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(0, 0, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(0, 30, 113, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(0, 120, 113, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(0, 150, 113, 22))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.name = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(120, 0, 211, 21))
        self.name.setObjectName("name")
        self.amount_of_roasting = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.amount_of_roasting.setGeometry(QtCore.QRect(120, 30, 211, 21))
        self.amount_of_roasting.setObjectName("amount_of_roasting")
        self.value = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.value.setGeometry(QtCore.QRect(120, 120, 211, 21))
        self.value.setObjectName("value")
        self.amount_of_ml = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.amount_of_ml.setGeometry(QtCore.QRect(120, 150, 211, 21))
        self.amount_of_ml.setObjectName("amount_of_ml")
        self.confirmation = QtWidgets.QPushButton(self.centralwidget)
        self.confirmation.setGeometry(QtCore.QRect(0, 200, 221, 28))
        self.confirmation.setObjectName("confirmation")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(0, 60, 113, 22))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(0, 90, 113, 22))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.way = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.way.setGeometry(QtCore.QRect(120, 60, 211, 21))
        self.way.setObjectName("way")
        self.taste = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.taste.setGeometry(QtCore.QRect(120, 90, 211, 21))
        self.taste.setObjectName("taste")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 517, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setText(_translate("MainWindow", "название:"))
        self.lineEdit_2.setText(_translate("MainWindow", "степень обжарки:"))
        self.lineEdit_3.setText(_translate("MainWindow", "цена в Р.:"))
        self.lineEdit_4.setText(_translate("MainWindow", "объём в МЛ.:"))
        self.confirmation.setText(_translate("MainWindow", "Внести изменения"))
        self.lineEdit_5.setText(_translate("MainWindow", "молотое/в зернах"))
        self.lineEdit_6.setText(_translate("MainWindow", "вкус"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
